### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by nakamuranaoko** [nakamuranaoko/Mini-4WD-Race-Management-App#23]
お疲れ様です。
Issueを作成いたしましたので、お手数ですがご確認お願いします。

■Webアプリの概要
ミニ四駆のレース大会記録アプリです。ミニ四駆の大会、イベントの日付、コース、タイム、使用マシンの情報を記録します。
それらをXにシェアできます。レース結果の管理とシェアが簡単に行えるツールです。

■1週間辺りの開発に向けられる時間
- 1週間あたり：15時間

■ProjectsのURL
https://github.com/users/nakamuranaoko/projects/2

■MVPリリースまで
- [x] rails new
- [x] Renderにデプロイ
- [x] トップページ
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] レース、マシン記録機能
- [x] レース記録一覧表示機能
- [x] x投稿機能
- [x] レース、マシン記録編集削除機能

■MVP後
- [ ] マシンの記録詳細登録機能
- [ ] 検索機能
- [ ] SNSログイン（Google認証）
- [ ] 大会記録カレンダー機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] お気に入りユーザー登録機能
- [ ] 投稿セーブ機能
- [ ] 写真スライダー機能

■MVPレビュー依頼予定日
予定日：2024年 12月 15日

**Comment by nakamuranaoko** [comment]
お疲れ様です。
すでに終わった分（README,画面遷移図,ER図,）+ issueの分解について、現在までに実際かかった時間としてストーリーポイント5を付与しておりました。ご指摘の通り３以下に訂正いたしましたので、再度ご確認お願いします。

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
- ログイン機能を実装するissueはありますが、ログアウトの機能を実装するissueが見当たらなかったので確認をお願いします。

**Comment by nakamuranaoko** [comment]
お疲れ様です。
「ログイン機能」の期待する動作に、ログアウトも含めてしまっておりました。
わかりにくくて、申し訳ございません。
下記の通り修正いたしましたのでご確認お願いします。

## 修正箇所
「ログアウト機能の実装」（ストーリーポイント１）を追加いたしました。

なお、この変更により「ログイン機能の作成」のストーリーポイントを　3 → 2 に変更いたしました。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- Xシェア

**Comment by nakamuranaoko** [comment]
ご確認ありがとうございました！
MVPの期日が大幅に遅れそうでしたら、
・Xシェア
